### ISSUE TITLE
IL2CPP Testing

### ISSUE THREAD

**Issue by yourpalmark** [strangeioc/strangeioc#126]
Is anyone on the beta of IL2CPP support in Unity 4.6 or 5?
Has StrangeIoC been tested to make sure it works fine with it?

Background of this request is that Apple is requiring 64-bit support by February 1st, and according to Unity, they "are going to support iOS 64-bit via IL2CPP in Unity 4.6.x and Unity 5.":

http://blogs.unity3d.com/2014/12/23/rd-christmas-update/

**Comment by bberryEA** [comment]
I've observed one initial issue firing up a project under IL2CPP for the first time (Unity 4.6.1p5):

IL2CPP error for type '<PrivateImplementationDetails>' in assembly '/XXXXXXXXX/YYYYYY/ZZZZZZZ.dll'
Additional information: Build a development build for more information. Interface strange.extensions.injector.api.IInjectionBinder method System.Void strange.extensions.injector.api.IInjectionBinder::Unbind(System.Object) not implemented on non-abstract class strange.extensions.injector.impl.InjectionBinder

Given a quick look at the code, the statement above appears to be true.

Might be a case of IL2CPP making incorrect assumptions, but it could also be something remedied with full (if hoop) interface implementation at all concrete levels.  Or perhaps something else.

We'll obviously check with the Unity folks, too, but we were curious to get your thoughts as well.

Cheers.

**Comment by bberryEA** [comment]
Actually, I see that this (and a family of other methods) are declared both at the IInjectionBinder interface as well as the IBinder interface (the latter being what C# resolves for concrete InjectionBinder).  This may be confusing the translation, since the methods are same-signature but not same-origin?

**Comment by WillzZz** [comment]
Well, everything you said is true. That doesn't help me understand the problem much. I'm genuinely surprised this fails, as it would be a problem with multi interface implementation. Have you reached anyone at Unity about this issue? If this is an easy repro (which I guess it is!) I'll poke someone on the scripting team tomorrow. I assume you're building iOS 64-bit.

**Comment by bberryEA** [comment]
I did file a bug with them, with a nice and tidy example project to assist them.  I'll try and remember to comment here if/when there is resolution.   Thanks for the response.

**Comment by WillzZz** [comment]
Of course. Just so you know, Marc and I both work at Unity, so let me know if you need any help.

**Comment by jnbt** [comment]
As Unity has released 4.6.2 together with 64bit support I'm just trying to get my project running.

Just to let you know I'm facing a `EXC_BAD_ACCESS` with the IInjectionBinder during runtime at:

 ```cpp
Object_t3 * L_0 = (Object_t3 *)GenericInterfaceFuncInvoker0< Object_t3 * >::Invoke(&IInjectionBinder_Bind_m16519_MethodInfo, ___injectionBinder);
```

This directly occurs on the first binding: 
```csharp
injectionBinder.Bind<IAnInterface>().To<AClass>();
```

**Comment by damiantrimboli** [comment]
Can you post a link to the bug filed? So I can follow it too? I'm having the same problem.

**Comment by WillzZz** [comment]
667053. Looking at this now.

**Comment by WillzZz** [comment]
Pretty sure the fix is just to override and implement the method such that it's always referencing it and will not strip the method. Downloading the newest 4.6.2 to verify.

**Comment by bberryEA** [comment]
@damiantrimboli : http://fogbugz.unity3d.com/default.asp?667053_s336hlu9pnf68olu

@WillzZz : I wouldn't be surprised if there was a way to massage StrangeIoC to be friendly to IL2CPP as it stands now.  I don't think you should have to, though---the IL2CPP folks should (and, I assume, are) working feverishly to close all of the feature / conformance gaps evident in these early releases.   (Having said that, if you push tweaks to the library, we'll certainly give them a try too.)  Cheers.

**Comment by WillzZz** [comment]
I agree, it should be possible to fix. I put a bunch of hours in to it last night, but have a different machine at home so having trouble reproing. Don't worry, I'll get this figured out. We have a lot of priority internally to get il2cpp to a rock solid state, this is just another improvement to add :) 

If you'd like to look at things, I made progress by implementing the "missing" Bind<T>(object key) method in InjectionBinder. I'm now running in to what appears to be InjectionBinder having GetBinding<T>() being stripped for some reason. It blows up in SignalCommandBinder in Unbind<T>(). I haven't been able to determine why that is, yet.

**Comment by WillzZz** [comment]
Hearing we have some progress on this. Can't really clarify but we've found the root cause. We have lots of Bind and Unbind methods :) I'll let you know ASAP when a patch is incoming. In the meantime I think using the Bind(Type type) and Unbind(Type type) methods might be temporary workarounds. If this is necessary for a release let me know and I can write a quick workaround branch to fix things like SignalCommandBinder. You can always shoot me a personal email at wcorwin aaatttt gmail com or skype at will.corwin (In Seattle) if necessary.

**Comment by WillzZz** [comment]
Official response: Thanks for reporting this issue. It has now been fixed and the fix should be included in 4.6.2p1.

**Comment by bberryEA** [comment]
Thanks a bunch, we'll be looking.

**Comment by yourpalmark** [comment]
Not quite clear on the resolution of this issue.
Are you saying it should be fixed in 4.6.2p1 with no updates to the Strange library? Or are you saying with 4.6.2p1 AND an update to the Strange library, this issue is resolved?

I ask because I am on Unity 4.6.3 (with an older version of Strange) testing and still run into the SignalCommandBinder Bind crash getting a generic interface.

I understand that there are workarounds by using the non-generic version, but that isn't truly a resolution. That's just a workaround.

Should this issue be closed?

**Comment by WillzZz** [comment]
This wasn't a strange issue, it was an il2cpp issue. It should be fixed. If it isn't we can look in to it again and try to address it in a new 4.6 patch.

**Comment by yourpalmark** [comment]
Ok, that's what I gathered as well. But just wanted to make sure since I am still getting the crash.
Is there anything I can provide to assist debugging?

**Comment by WillzZz** [comment]
4.6.3p2 has several fixes for il2cpp. I'm not sure when that releases, but it'll be very soon.

**Comment by Qarn** [comment]
Hello, I'm joining in a bit late here, but I'm running into a similar issue to the UnusedBytecodeStripper2.exe issue mentioned earlier. I'm using the new Unity 5 when deploying to WebGL.  The same issue was present in the beta version.

I'm wondering if you have any idea if these fixes will also be in Unity 5 soon?

**Comment by yourpalmark** [comment]
4.6.3p2 fixes the SignalCommandBinder crash.

I'll post on the [open thread](https://github.com/strangeioc/strangeioc/issues/136) if there are any other issues.

**Comment by bberryEA** [comment]
Yep, we can confirm that too here.  Many thanks!

**Comment by JiboStore** [comment]
does anyone know of a way to prevent stripping in IL2CPP? I'm having a different crash due to stripping problem..

**Comment by WillzZz** [comment]
Assembly-CSharp shouldn't be stripped, but UE.dll will be stripped at the method level. You can use link.xml to address it, or you can reference the class in code.

**Comment by jean-noelp** [comment]
**Solution** : add a "link.xml" file into your assets, with this content :
`<linker>
     <assembly fullname="DLLName1" preserve="all"/>
     <assembly fullname="DLLName2" preserve="all"/>
     <assembly fullname="DLLName3" preserve="all"/>
</linker>`

Note : do not write ".dll" extension in your DLLNames.
