### ISSUE TITLE
IL2CPP in Unity 5 - issues with: Binding / Virtual Generic methods

### ISSUE THREAD

**Issue by Andraxb** [strangeioc/strangeioc#136]
Anyone been using StrangeIoC in Unity 5 (currently rc3) with StrangeIoC and ran into the issue similar(probably the same as it's related to Binding) to the one described here: https://github.com/strangeioc/strangeioc/issues/126

If I build it with any architecture and IL2CPP, then try to run on a device I run into an EXC_BAD_ACCESS error at:
#0	0x0180a010 in il2cpp::vm::Runtime::GetGenericInterfaceInvokeData(MethodInfo*, void*) at /Users/builduser/buildslave/unity/build/Tools/il2cpp/il2cpp/libil2cpp/vm/Runtime.cpp:575
#1	0x001d8c04 in GenericInterfaceFuncInvoker0<Object_t*>::Invoke(MethodInfo*, void*) at ~/Classes/Native/GeneratedGenericInterfaceInvokers.h:19
#2	0x00bf3680 in SignalCommandBinder_Bind_TisObject_t_m56290_gshared(SignalCommandBinder_t266*, MethodInfo*) at ~/Classes/Native/GenericMethods12.cpp:23213

I noticed it got fixed in Unity 4.6.2p1, but I'm still running into this error in Unity 5, any idea if this (should) have been fixed in Unity 5 as well?

Also reported this a while ago at Unity but haven't had a response yet (issueid: 670637).

**Comment by jnbt** [comment]
Have you tried to use the non-generic version of `Bind`. This helped me before Unity 4.6.3

e.g. 

```csharp
injectionBinder.Bind<IApi>().To<MyApi>();
// ->
injectionBinder.Bind(typeof(IApi)).To(typeof(MyApi));
```

**Comment by WillzZz** [comment]
I'm not sure if rc4 or rc3 has the most up to date il2cpp fixes that 4.6.3 has. I just built a new machine at home and will be messing with rc4 later today. I'll see what I run in to and update you guys.

**Comment by Andraxb** [comment]
Thanks for the reply it's good to know IL2CPP is still being worked on at Unity, the Unity 5 rc3 release notes had no IL2CPP fixes so I got worried a bit.

I have tried using the non-generic version of Bind, can't get it to work with the SignalCommandBinder however. Also tried a suggestion posted here ( http://forum.unity3d.com/threads/4-6-ios-64-bit-beta.290551/ ) of instantiating the generic classes(Signals in this case) once before injecting so IL2CPP compiles the classes. 

Don't have the time to try any further right now sadly, hoping it gets @ Unity before I do have the time!

**Comment by bberryEA** [comment]
FWIW, this still occurs for us with 4.6.3p1, so reports that it has been eradicated in 4.x are premature.  Anyone have a minimal snippet they successfully used to provoke this before?  (Will save me some time from pruning a large project to generate one.)  I'll happily file a support issue with Unity to have it addressed.

**Comment by richard-nmtrix** [comment]
Same here, the issue still exists in 4.6.3p1. GetGenericInterfaceInvokeData returns a data object with a null methodinfo on iOS builds running on a device.

You can reproduce it by cloning Strange Rocks and running it on an iPad or phone. The only thing I changed was the code generation setting (IL2CPP enabled instead of Mono - set to ARM v7 instead of Universal for compilation speed).

The non-generic method trick does not work. At least, not when using SignalCommandBinder.

**Comment by bberryEA** [comment]
Perfect.  Thanks for that info.

**Comment by yourpalmark** [comment]
Yeah, I commented on the [original issue](https://github.com/strangeioc/strangeioc/issues/126) letting them know the issue isn't solved in 4.6.3 either.

It sounds like 4.6.3p2 will have some IL2CPP fixes in it, so perhaps it'll be fixed.

I'll leave this to the Strange guys to answer, but since at this point this is a Unity issue and not a Strange issue do you want us to comment on the original issue, this issue, or somewhere else just to keep you guys aware as Unity releases new patches, etc?

**Comment by WillzZz** [comment]
I appreciate the feedback here to give me an idea of the state of il2cpp and strange. Clearly it's not working in il2cpp right now. That's bad. The good news is I'm 90% sure it was already fixed and we're just waiting for the code to hit release. Thanks for all of the updates, guys! I'll for sure mention it to some people while we're in SF.

**Comment by richard-nmtrix** [comment]
FYI: I've just tried to run the Strange Rocks project with Unity 5 (5.0.0f4, the version released today), but unfortunately the issue still exists.

**Comment by bberryEA** [comment]
I have filed a support issue with Unity using strangerocks as the test case.

FWIW, a local change of SignalCommandBinder's override public ICommandBinding Bind<T>() to employ non-generic GetBinding(), Bid(), GetInstance() calls got us past this one (and onto others).  It looked like strangerocks had numerous issues downstream issues, though---whether due to incorrectness in our change or other issues.

**Comment by richard-nmtrix** [comment]
That change did indeed work, thanks!

And just to confirm, 4.6.3p2 fixes the issue as well. It's now possible to normally use SignalCommandBinder without having it call a non-generic version of Bind().

The leftover issues in StrangeRocks are caused by a bug with the injected Camera. There's no c'tor in it (on IL2CPP builds). Will look into this when I've got some more time and post a new bug report if needed.

I guess we'll only have to wait on a patch release with an up to date version of IL2CPP for Unity 5 now!

**Comment by WillzZz** [comment]
I'll keep this issue open until we get the patch for 5.0. I don't know when that will be. It should be fast. If I could get some more confirmations, that would be great.

If we find any new issues, let me know.

**Comment by bberryEA** [comment]
@richard-nmtrix Did you ever identify root cause for the injected camera issues?  It looks like we have just run into something similar.  (If you have a bug reported, let me know the case number for reference.)

**Comment by bberryEA** [comment]
(Actually, I think your explanation above is indeed root cause---but let me know if you've not yet filed a bug and I'll do so.)

**Comment by bberryEA** [comment]
(Case filed, just in case. :)).

**Comment by bberryEA** [comment]
This appears to just be a stripping issue.  If you simply new Camera() somewhere, it hints enough to get past this.   I will update the bug accordingly.

**Comment by WillzZz** [comment]
Oh, interesting. That's pretty silly. I understand why it's happening but I thought we had mechanisms to prevent that sort of thing. 

For the record, we should not be stripping methods from assembly-csharp, but since we don't explicitly reference Camera ctor I suppose it's stripped from UE.dll. Crazy! What's the fogbugz case? I'll keep an eye on it and see when we're getting it.

**Comment by bberryEA** [comment]
679540.   There are a number of further issues downstream due to the well known generic type creation issues with [Container]<T> etc. that should be addressed once that is resolved.  I started plopping in static declarations for each to clear each of them but didn't quite finish before going back to try the camera workaround in our own build.

**Comment by bberryEA** [comment]
Formatting goof above.  Fogbugz case 679540.

**Comment by jayallanjethwa** [comment]
The issue appears to be fixed with 5.0.0p1 (released yesterday, 2015-03-16).

**Comment by JayJayZZ** [comment]
Update: With the new Camera(); fix, I was able to make it to StrangeRock's main screen. However, then the following exception happens:

´´´
NotSupportedException: Failed to construct generic type 'strange.extensions.pool.impl.Pool`1' with generic arguments [strange.examples.strangerocks.game.CreateEnemyCommand] at runtime.
  at System.Type.MakeGenericType (System.Type gt, System.Type[] types) [0x00000] in <filename unknown>:0 
  at System.Type.MakeGenericType (System.Type[] typeArguments) [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.extensions.command.impl.CommandBinder.makePoolFromType (System.Type type) [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.extensions.command.impl.CommandBinder.resolver (IBinding binding) [0x00000] in <filename unknown>:0 
  at strange.framework.impl.Binder+BindingResolver.Invoke (IBinding binding) [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.extensions.command.impl.CommandBinding.Pooled () [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.examples.strangerocks.game.GameContext.mapBindings () [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.extensions.context.impl.Context.Start () [0x00000] in <filename unknown>:0 
  at strange.extensions.reflector.impl.ReflectionException.get_type () [0x00000] in <filename unknown>:0 
  at strange.extensions.context.impl.Context..ctor (System.Object view, ContextStartupFlags flags) [0x00000] in <filename unknown>:0 
  at strange.extensions.context.impl.Context..ctor (System.Object view) [0x00000] in <filename unknown>:0 
  at strange.extensions.context.impl.CrossContext..ctor (System.Object view) [0x00000] in <filename unknown>:0 
  at strange.extensions.context.impl.MVCSContext..ctor (UnityEngine.MonoBehaviour view) [0x00000] in <filename unknown>:0 
  at strange.examples.strangerocks.SignalContext..ctor (UnityEngine.MonoBehaviour contextView) [0x00000] in <filename unknown>:0 
  at strange.examples.strangerocks.game.GameContext..ctor (UnityEngine.MonoBehaviour contextView) [0x00000] in <filename unknown>:0 
  at strange.examples.strangerocks.game.GameBootstrap.Start () [0x00000] in <filename unknown>:0 
  at UnityEngine.Events.UnityAction.EndInvoke (IAsyncResult result) [0x00000] in <filename unknown>:0 
UnityEngine.Events.UnityAction:EndInvoke(IAsyncResult)
´´´

**Comment by bberryEA** [comment]
Yes, this is what I was referring to in my 11 March comment.  The toolchain does not have a way to know at build time through static analysis type(s) that may need to be emitted when they are created dynamically, so the only current workarounds are for these cases to declare somewhere a 'strange.extensions.pool.impl.Pool<T> __unused;' or something similar for each T required, which will force IL2CPP to see the concrete declarations and then honor them.  It's not ideal, certainly, but it works.  Strangerocks will need the same for many of its types.  There are cases where this can occur where the type you need to hint at is private/internal and thus declarations will not work---I filed a bug about this and that should be addressed at some point.

**Comment by unitymarc** [comment]
I'm thinking a blog post on this topic would be helpful...explaining the current status of things and a recipe for getting through it. @bberryEA would you be willing to assist me with this? Either I'd write it up based on your information (then have you review it), or you could.

**Comment by WillzZz** [comment]
link.xml should solve this and remove the need for the concrete ctor call.

http://docs.unity3d.com/Manual/iphone-playerSizeOptimization.html

**Comment by bberryEA** [comment]
Agree, link.xml is a better solution for the Camera-specific issue and that is what we have adopted here as well.

**Comment by JayJayZZ** [comment]
Would it be possible to give a more detailed example on what to fix? As far as I could see within StrangeRocks, the only T that is used for IPool is GameObject. But neither new Pool() nor new Pool<GameObject>() and/or declaring them somewhere fixed the issue.

As for link.xml, what is the name of the assembly I would have to specify? How can I find out what kind of assemblies Unity is creating?

Thanks!

**Comment by bberryEA** [comment]
For the camera, an Assets/link.xml e.g.:
```
<?xml version="1.0" encoding="UTF-8" ?>
<linker>
       <assembly fullname="UnityEngine">
		<type fullname="UnityEngine.Camera" preserve="all"/>
       </assembly>
</linker>
```
I haven't looked at StrangeRocks since the initial fix, but if the code is attempting to dynamically generate a type and fails (the example above), it needs it.  Not all of them will be trivially identifiable on inspection, unfortunately---which is in part the same trouble IL2CPP has in trying to identify what's needed.  The exercise here is, for the moment, to simply declare a static for each you encounter (probably the bulk of the XXXCommand classes, I'd imagine).

**Comment by WillzZz** [comment]
Keep in mind that il2cpp is stripping at the method level, so link.xml is going to be a lot less of a pain usually.

**Comment by richard-nmtrix** [comment]
Sorry for the late reply. The pooling of commands (like in StrangeRocks) does not work after adding the generic type to link.xml and static declarations don't work either (not for me at least, perhaps I'm doing something wrong?). Fortunately, Unity did just add a workaround for these kind of situations in patch release 4.6.3p4. And probably 4.6.4 and the next patch release for Unity 5 later this week as well.

If you add an il2cpp_extra_types.txt file to your project with the following contents (plus the Camera declaration in link.xml), StrangeRocks with IL2CPP will run great on iOS:

<div>
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.CreateEnemyCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.CreateRockCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.DestroyEnemyCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.DestroyMissileCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.DestroyPlayerCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.DestroyRockCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.FireMissileCommand]
strange.extensions.pool.impl.Pool`1[strange.examples.strangerocks.game.MissileHitCommand]
</div>
.
See this page for more information about this file and other situations where MakeGenericType is used:
http://forum.unity3d.com/threads/il2cpp-type-makegenerictype-work-around.311926/

**Comment by JayJayZZ** [comment]
I can confirm that with Unity 5.0.0p3 and the il2cpp_extra_types.txt mentioned above, StrangeRocks indeed now runs fine on iOS with IL2CPP.

**Comment by yourpalmark** [comment]
Anyone aware of this bug that was resolved in the latest patch release for 4.6.4 (p1)?

(682258) - iOS/IL2CPP: Fixed a crash with StrangeIOC.

Would love to know what the issue was and what was resolved.

**Comment by WillzZz** [comment]
Looking at the commit, it looks like there was a problem retrieving a BaseDefinition of a method info for a generic, inherited method. Having trouble seeing where we do that exact thing, but it sounds like something I would do :)

**Comment by yourpalmark** [comment]
Sounds like it *might* fix my bug:
http://fogbugz.unity3d.com/default.asp?685778_1hfrrgaupdhaug4a
